### ISSUE TITLE
Missing functionality checklist

### ISSUE THREAD

**Issue by myleshorton** [getlantern/httpseverywhere#1]
- [x] Support for exclusions
- [x] Support for secure cookies
- [x] Support for disabled rules
- [x] Support for mixed content flag
- [x] Support for downgrade rules

**Comment by myleshorton** [comment]
We can't set secure cookie attributes since we can't see the HTTPS traffic, so I think we're out of luck there.

**Comment by myleshorton** [comment]
I think we're also going to skip downgrade rules -- there are very few of them, but also AFAICT the only place they would be valid is in Tor where mixed content is allowed.
